[build]
base = ""
command = "yarn build:prod"
publish = "dist"
ignore = "git diff --quiet HEAD^ HEAD docs/ images/ netlify.toml package.json yarn.lock .node-version"

[[plugins]]
package = "netlify-plugin-minify-html"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs]
fail_deploy_on_score_thresholds = "true"

[plugins.inputs.thresholds]
accessibility = 1
best-practices = 1
seo = 1
