[build]
base = ""
command = "npm run build:prod"
publish = "docs/.vitepress/dist"
ignore = "git diff --quiet HEAD^ HEAD docs/ netlify.toml package.json package-lock.json .node-version"

[build.processing]
skip_processing = true

[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs]
fail_deploy_on_score_thresholds = "true"

[plugins.inputs.thresholds]
accessibility = 1
best-practices = 1
seo = 1

[[redirects]]
  from = "/fr/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/misc/applepressandholdenabled.html"
  to = "/keyboard/applepressandholdenabled.html"
  status = 301
  force = true
